"""Utility modules for constants, helpers, and stat calculations."""

# Constants
from .constants import (
    BASE_DIR,
    CACHE_DIR,
    REFERENCES_DIR,
    DEFAULT_INPUT_DIR,
    BASIC_STATS,
    ADVANCED_STATS,
    FOUR_FACTORS_STATS,
    ALL_STATS,
    DATE_FORMATS,
    TEAM_CODES,
    CODE_TO_TEAM,
    CONFERENCES,
    CONFERENCE_HISTORY,
    TEAM_ALIASES,
    MILESTONE_THRESHOLDS,
    MILESTONE_BASE_COLUMNS,
    PLAYER_BASE_COLUMNS,
    DECIMAL_2_CENTER,
    DECIMAL_3_CENTER,
    INTEGER_CENTER,
    COMMA_NUMBER,
    DATE_CENTER,
    PERCENTAGE_1,
    EXCEL_COLORS,
    GID_SPLIT_RE,
    GID_DATE_RE,
    SPORTS_REF_PLAYER_URL,
    SPORTS_REF_GAME_URL,
    get_conference,
    get_conference_for_date,
)

# Helpers
from .helpers import (
    normalize_name,
    get_team_code,
    parse_date,
    format_date_yyyymmdd,
    generate_game_id,
    parse_minutes,
    safe_int,
    safe_float,
    create_sports_ref_hyperlink,
    extract_player_id_from_href,
    calculate_game_score,
    sort_games_by_date,
)

# Stat utilities
from .stat_utils import (
    calculate_fg_pct,
    calculate_efg_pct,
    calculate_ts_pct,
    calculate_per_game_stats,
    calculate_shooting_percentages,
    is_double_double,
    is_triple_double,
    get_double_double_categories,
    is_hot_shooting,
    is_perfect_ft,
    aggregate_player_stats,
    calculate_pace,
    calculate_usage_rate,
    calculate_offensive_rating,
    calculate_defensive_rating,
    calculate_per,
    calculate_four_factors,
    is_near_double_double,
    get_near_double_double_detail,
)

# Logging
from .log import info, warn, set_verbosity, set_use_emoji

__all__ = [
    # Constants
    'BASE_DIR',
    'CACHE_DIR',
    'REFERENCES_DIR',
    'DEFAULT_INPUT_DIR',
    'BASIC_STATS',
    'ADVANCED_STATS',
    'FOUR_FACTORS_STATS',
    'ALL_STATS',
    'DATE_FORMATS',
    'TEAM_CODES',
    'CODE_TO_TEAM',
    'CONFERENCES',
    'CONFERENCE_HISTORY',
    'TEAM_ALIASES',
    'MILESTONE_THRESHOLDS',
    'MILESTONE_BASE_COLUMNS',
    'PLAYER_BASE_COLUMNS',
    'DECIMAL_2_CENTER',
    'DECIMAL_3_CENTER',
    'INTEGER_CENTER',
    'COMMA_NUMBER',
    'DATE_CENTER',
    'PERCENTAGE_1',
    'EXCEL_COLORS',
    'GID_SPLIT_RE',
    'GID_DATE_RE',
    'SPORTS_REF_PLAYER_URL',
    'SPORTS_REF_GAME_URL',
    'get_conference',
    'get_conference_for_date',
    # Helpers
    'normalize_name',
    'get_team_code',
    'parse_date',
    'format_date_yyyymmdd',
    'generate_game_id',
    'parse_minutes',
    'safe_int',
    'safe_float',
    'create_sports_ref_hyperlink',
    'extract_player_id_from_href',
    'calculate_game_score',
    'sort_games_by_date',
    # Stat utilities
    'calculate_fg_pct',
    'calculate_efg_pct',
    'calculate_ts_pct',
    'calculate_per_game_stats',
    'calculate_shooting_percentages',
    'is_double_double',
    'is_triple_double',
    'get_double_double_categories',
    'is_hot_shooting',
    'is_perfect_ft',
    'aggregate_player_stats',
    'calculate_pace',
    'calculate_usage_rate',
    'calculate_offensive_rating',
    'calculate_defensive_rating',
    'calculate_per',
    'calculate_four_factors',
    'is_near_double_double',
    'get_near_double_double_detail',
    # Logging
    'info',
    'warn',
    'set_verbosity',
    'set_use_emoji',
]
